### ISSUE TITLE
Is Apache Karaf mandatory to build and use Kapua?

### ISSUE THREAD

**Issue by sebascarra** [eclipse-kapua/kapua#2847]
I am attempting to build Kapua in a restricted environment. Long story short, I can only build Kapua if I comment out the following in ./client/gateway/features/pom.xml, basically leaving out the sub-project kapua-client-gateway-feature-karaf:

    <!-- <modules>
        <module>karaf</module>
    </modules>

Is it mandatory to have this component or can I completely forget about it and build Kapua and connect it to Kura nonetheless?

Thank you.

**Comment by Coduz** [comment]
Hi @sebascarra ,

if you want to specifically exclude modules from the build (specifically exclude them from the reactor build list) maven has a built it option to do that.

You can use the `--projects` (`-pl`) option. Here is some example of usage [1] 
In this case, to exclude that module you should use
```
mvn clean install -pl !:kapua-client-gateway-feature-karaf    
```

Depending on the terminal you are using, the `!` must be escaped, so you likely have to issue the following command:
```
mvn clean install -pl \!:kapua-client-gateway-feature-karaf    
```

The module `kapua-client-gateway-feature-karaf` is not required by Kapua in order to work and this is true for all modules under `kapua-client`.

Regards, 

_Alberto_

[1] https://blog.sonatype.com/2009/10/maven-tips-and-tricks-advanced-reactor-options/

**Comment by sebascarra** [comment]
Thank you @Coduz for the response. I will ask separately what components could be considered optional for Kapua to work alongside Kura gateways. The reason is that we have to run Kapua and Kura in a safe environment and we've found some components (e.g. Karaf 4.1.1, used in Kapua 1.1.0 and 1.1.1) have vulnerabilities.

**Comment by sebascarra** [comment]
@Coduz I have created issue https://github.com/eclipse/kapua/issues/2848 wher I ask what are the strictly required Kapua components for a successful build. Maybe you know the answer because I'm likely to have issues with other components as well.

Thank you.

**Comment by Coduz** [comment]
Hi @sebascarra ,

No problem.

Regarding components that have vulnerabilities we are working to slowly move forward dependency versions to allow those to be solved and to keep the pace with our dependencies's new versions.

Unfortunately we cannot upgrade straightforward to the last version available since there are  some procedures that must be followed in order to have them approved. 

I''l close this issue and follow to the new one opened

Regards, 

- Alberto
