### ISSUE TITLE
Pure node client for Kapua from SwiftSense

### ISSUE THREAD

**Issue by swiftconnect** [eclipse-kapua/kapua#3082]
We have a pure node (actually node-red) client for Kapua that is :
- Do MQTT-over-TLS connectivity with Kapua
- Able to register in Kapua console as a device
- Send data to Kapua 
- Provide a CMD-V1 application to receive commands
- Provide a CONFIG-V1 application to allow Kapua based configuration management 

We have run our Kapua installation with limited commercial loads (upto 50-60 clients) with great results so far. Our longest running client has an uptime of nearly 1 year 
Kapua is fabulous of course - rock solid! But we also believe a part of the success can be attributed to how light (our Java clients were much heavier) the client system is. 

We are now looking to take this forward. But since our architecture is so heavily dependent on Kapua we would like to see if there is a possibility that we could work more closely with you guys. Would appreciate your feedback at your earliest convenience.
The 
SwiftSense Team

**Comment by lorthirk** [comment]
Hey @swiftconnect, thanks for reaching out.

What kind of feedback do you have in mind exactly?

**Comment by swiftconnect** [comment]
Going forward we want to look at several core functional areas for example:

- Possibility of upgrading elasticsearch (current versions work with 5.4)
- Hooking up Kapua to an existing ES cluster (rather than clustering the entire pod as one)
- Switching ES for a different TSDB like Influx
- Exposing the message routing process (currently it seems to be very much kept under wraps)
- And others

Are these valid and timely questions in the context of the road map as you guys see it? 
Or should we assume that these would not be considered and we should not expect anything to happen on these line?
Thanks

**Comment by lorthirk** [comment]
For sure we're going to do something about upgrading Elasticsearch. I already started a branch for this but we have to plan the upgrade path carefully. Also using an external ES cluster should be already possible since the cluster address is configurable. As for the other points I think we would need additional investigation, so feel free to open issues for those or get in touch in the [Gitter Room](https://gitter.im/eclipse/kapua)

**Comment by swiftconnect** [comment]
Thanks for your response Claudio.
Would it be possible to discuss the overall setup with you directly over a
call? Basically we want to ensure that we align our roadmap with yours.
If we move ahead with Kapua in production, it will take the system a long
time to grow to the millions of nodes projected. But we need to ensure that
we get the basics right the first time.

**Comment by swiftconnect** [comment]
For example - the upgrade path for ES is very important for us. We are
unable to continue at all with 5.4 any further.
Would be great to understand these roadmap items

**Comment by riccardomodanese** [comment]
Hello,
    thank you for your feedback, it's really appreciated.

Recently we had some difficulties keepinga regular schedule for Kapua meeting and we are working to reestablish them as soon as possible.
In the meanwhile we can arrange a spot call.
We are more or less CET based.
Do you have any day/hour preference?

**Comment by swiftconnect** [comment]
Hello Riccardo 
Thank you for your message. I think an agenda based call will be very useful - at least for now. 
We are Singapore based and happy to work with your timings. 
Looking forward to hearing from you
Thanks, 
The SwiftSense Team

**Comment by lorthirk** [comment]
Well, I think this kind of discussion would perfectly fit the Kapua Community Meeting, that is scheduled next for next Thursday ad 14:30 CET at the usual address https://bluejeans.com/192143067. Would that work for you? We can arrange a separate call if not.

**Comment by swiftconnect** [comment]
Is that 5Nov 1430 CET? If so that would be fine.
Thank you

**Comment by lorthirk** [comment]
No, the next scheduled meeting is for tomorrow, October 28th, otherwise it would be November, 12th... in other words, every other Thursday 😄 

If those dates don't suit you, feel free to contact me by email or the [Gitter.im room](https://gitter.im/eclipse/kapua) so we can arrange a meeting whenever you are comfortable.

**Comment by swiftconnect** [comment]
Fantastic - there's no point adding to overhead. We'll join in tomorrow and take things from there. 
Many thanks for the introduction

**Comment by lorthirk** [comment]
So... we had the meeting but it seems you guys didn't manage to get in. Let's keep in touch for an update!

**Comment by swiftconnect** [comment]
Our loss - we got pulled into a last minute thing and are out just now. 
I think the next standard update will happen in 2 weeks time? We definitely want to be in on that - but if there is an opportunity in between we would not mind. Do let us know.

**Comment by lorthirk** [comment]
Yes, next meeting would be November, 12th. However I see no problems in having a separate call whenever you're available.

However, in order to arrange it, I would discuss it in the [Eclipse Kapua Mailing List](https://accounts.eclipse.org/mailing-list/kapua-dev) so that every member of the community who might be interested in joining the call is informed.

If that's ok I would also close this issue, since its original purpose has been answered. 

Thank you again for your interest in Kapua!

**Comment by swiftconnect** [comment]
Hi @lorthirk - thank you for following up. We are going to try and attend the meeting on the 12th.
We assume the timing is still the same?
Regards.

**Comment by lorthirk** [comment]
Exactly, still 14:30 CET (GMT+1)

**Comment by swiftconnect** [comment]
Lost the links in the chat unfortunately! Would you have them handy?
Thanks a lot!

**Comment by riccardomodanese** [comment]
you are welcome!

gitter: https://gitter.im/eclipse/kapua
mailing list: https://accounts.eclipse.org/mailing-list/kapua-dev

**Comment by lorthirk** [comment]
So, after the Community Meeting I guess this can be closed. Thanks anyone for joining!
