### ISSUE TITLE
Should "travis.yml" File be Removed? 

### ISSUE THREAD

**Issue by LeoNerdoG** [eclipse-kapua/kapua#3192]
After merging PR #3182 the default CI is actually GitHub. Should we therefore remove the "travis.yml" file and update the codecov.yml file? 

**Testflow:**
 - there is no testflow for this issue. 

**Expected behavior**
I would expect that "travis.yml" file is no longer needed? 

**Screenshots**
![Screenshot 2021-01-13 at 14 21 23](https://user-images.githubusercontent.com/15121999/104457703-ab334f80-55aa-11eb-95b3-f4f5940e4fcb.png)

**Version of Kapua**
latest develop branch

**Additional context**
/

**Comment by gbarbon** [comment]
Hi @LeoNerdoG , yes, the `travis.yaml` file should be removed in the future, but we decided to keep it for a period in order to double check the results of the GitHub Actions (see also the 'side note' in PR #3182 ). We can use this issue to remember ourselves to do the removal as soon as we're sure that results are ok.

**Comment by Coduz** [comment]
I think that it will remain there until Travis.org works. 
When they shut down it, instead of migrating to Travis.com we can remove it.

**Comment by LeoNerdoG** [comment]
This has been resolved with PR #3237 (travis.yml file has been removed). Closing.
